# ====> Bank Loan Default Prediction Using Machine Learning

#### Banks provide loans to customers, but some customers fail to repay them, causing financial losses. Predicting whether a customer is likely to default before approving a loan can help banks reduce risk and make better lending decisions.

#### Objective:
#### Develop a machine learning model that predicts whether a customer will default on a loan based on their personal, financial, and loan-related information.
#### ===========================================================================================

#### => Dataset Summary
#### Dataset Name: Loan Default Prediction Dataset

#### Domain: Banking / Finance

#### Target Variable: Default (or Loan_Status, depending on the dataset)

#### 0 = No Default
#### 1 = Default
#### ===========================================================================================
#### Feature Categories
#### ===========================================================================================

#### => Numerical Features
#### - Age
#### - Income
#### - LoanAmount
#### - CreditScore
#### - MonthsEmployed
#### - NumCreditLines
#### - InterestRate
#### - LoanTerm
#### - DTIRatio


#### => Categorical Features
#### - Education
#### - EmploymentType
#### - MaritalStatus
#### - HasMortgage
#### - HasDependents
#### - LoanPurpose
#### - HasCoSigner


#### => Identifier
#### - LoanID


#### => Target Variable
#### - Default


#### => Total Features
#### - 1 Identifier: LoanID
#### - 9 Numerical Features
#### - 7 Categorical Features
#### - 1 Target Variable: Default
#### Total Columns = 18

#### ===========================================================================================

=> Feature 
| Feature        | Description                                       | Type                 |
| -------------- | ------------------------------------------------- | -------------------- |
| LoanID         | Unique loan ID                                    | Categorical          |
| Age            | Age of the applicant                              | Numerical            |
| Income         | Annual income of the applicant                    | Numerical            |
| LoanAmount     | Amount of loan requested                          | Numerical            |
| CreditScore    | Applicant's credit score                          | Numerical            |
| MonthsEmployed | Total months employed                             | Numerical            |
| NumCreditLines | Number of active credit lines                     | Numerical            |
| InterestRate   | Loan interest rate (%)                            | Numerical            |
| LoanTerm       | Loan repayment period (months)                    | Numerical            |
| DTIRatio       | Debt-to-Income ratio                              | Numerical            |
| Education      | Highest education level                           | Categorical          |
| EmploymentType | Type of employment                                | Categorical          |
| MaritalStatus  | Marital status                                    | Categorical          |
| HasMortgage    | Whether the applicant has a mortgage              | Categorical (Yes/No) |
| HasDependents  | Whether the applicant has dependents              | Categorical (Yes/No) |
| LoanPurpose    | Purpose of the loan                               | Categorical          |
| HasCoSigner    | Whether the loan has a co-signer                  | Categorical (Yes/No) |
| **Default**    | **Target variable (0 = No Default, 1 = Default)** | **Target**           |


#### ===========================================================================================

In [2]:
import pandas as pd

df = pd.read_csv("Loan_default.csv")
#1
df.head(df.shape[0])

,LoanID,Age,Income,LoanAmount,CreditScore,MonthsEmployed,NumCreditLines,InterestRate,LoanTerm,DTIRatio,Education,EmploymentType,MaritalStatus,HasMortgage,HasDependents,LoanPurpose,HasCoSigner,Default
0,I38PQUQS96,56,85994,50587,520,80,4,15.23,36,0.44,Bachelor's,Full-time,Divorced,Yes,Yes,Other,Yes,0
1,HPSK72WA7R,69,50432,124440,458,15,1,4.81,60,0.68,Master's,Full-time,Married,No,No,Other,Yes,0
2,C1OZ6DPJ8Y,46,84208,129188,451,26,3,21.17,24,0.31,Master's,Unemployed,Divorced,Yes,Yes,Auto,No,1
3,V2KKSFM3UN,32,31713,44799,743,0,3,7.07,24,0.23,High School,Full-time,Married,No,No,Business,No,0
4,EY08JDHTZP,60,20437,9139,633,8,4,6.51,48,0.73,Bachelor's,Unemployed,Divorced,No,Yes,Auto,No,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
255342,8C6S86ESGC,19,37979,210682,541,109,4,14.11,12,0.85,Bachelor's,Full-time,Married,No,No,Other,No,0
255343,98R4KDHNND,32,51953,189899,511,14,2,11.55,24,0.21,High School,Part-time,Divorced,No,No,Home,No,1
255344,XQK1UUUNGP,56,84820,208294,597,70,3,5.29,60,0.50,High School,Self-employed,Married,Yes,Yes,Auto,Yes,0
255345,JAO28CPL4H,42,85109,60575,809,40,1,20.90,48,0.44,High School,Part-time,Single,Yes,Yes,Other,No,0
255346,ZTH91CGL0B,62,22418,18481,636,113,2,6.73,12,0.48,Bachelor's,Unemployed,Divorced,Yes,No,Education,Yes,0

In [6]:
#2
df.describe()

,Age,Income,LoanAmount,CreditScore,MonthsEmployed,NumCreditLines,InterestRate,LoanTerm,DTIRatio,Default
count,255347.000000,255347.000000,255347.000000,255347.000000,255347.000000,255347.000000,255347.000000,255347.000000,255347.000000,255347.000000
mean,43.498306,82499.304597,127578.865512,574.264346,59.541976,2.501036,13.492773,36.025894,0.500212,0.116128
std,14.990258,38963.013729,70840.706142,158.903867,34.643376,1.117018,6.636443,16.969330,0.230917,0.320379
min,18.000000,15000.000000,5000.000000,300.000000,0.000000,1.000000,2.000000,12.000000,0.100000,0.000000
25%,31.000000,48825.500000,66156.000000,437.000000,30.000000,2.000000,7.770000,24.000000,0.300000,0.000000
50%,43.000000,82466.000000,127556.000000,574.000000,60.000000,2.000000,13.460000,36.000000,0.500000,0.000000
75%,56.000000,116219.000000,188985.000000,712.000000,90.000000,3.000000,19.250000,48.000000,0.700000,0.000000
max,69.000000,149999.000000,249999.000000,849.000000,119.000000,4.000000,25.000000,60.000000,0.900000,1.000000

In [7]:
#3
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 255347 entries, 0 to 255346
Data columns (total 18 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   LoanID          255347 non-null  object
 1   Age             255347 non-null  int64
 2   Income          255347 non-null  int64
 3   LoanAmount      255347 non-null  int64
 4   CreditScore     255347 non-null  int64
 5   MonthsEmployed  255347 non-null  int64
 6   NumCreditLines  255347 non-null  int64
 7   InterestRate    255347 non-null  float64
 8   LoanTerm        255347 non-null  int64
 9   DTIRatio        255347 non-null  float64
 10  Education       255347 non-null  object
 11  EmploymentType  255347 non-null  object
 12  MaritalStatus   255347 non-null  object
 13  HasMortgage     255347 non-null  object
 14  HasDependents   255347 non-null  object
 15  LoanPurpose     255347 non-null  object
 16  HasCoSigner     255347 non-null  object
 17  Default         255347 non-null  int64
dtypes: float64(2), int64(8), object(8)
memory usage: 35.1+ MB

In [20]:
#4
df.shape

(255347, 18)

In [23]:
#5
df.isnull().sum()

LoanID            0
Age               0
Income            0
LoanAmount        0
CreditScore       0
MonthsEmployed    0
NumCreditLines    0
InterestRate      0
LoanTerm          0
DTIRatio          0
Education         0
EmploymentType    0
MaritalStatus     0
HasMortgage       0
HasDependents     0
LoanPurpose       0
HasCoSigner       0
Default           0
dtype: int64

In [8]:
#6
df.columns

Index(['LoanID', 'Age', 'Income', 'LoanAmount', 'CreditScore',
       'MonthsEmployed', 'NumCreditLines', 'InterestRate', 'LoanTerm',
       'DTIRatio', 'Education', 'EmploymentType', 'MaritalStatus',
       'HasMortgage', 'HasDependents', 'LoanPurpose', 'HasCoSigner',
       'Default'],
      dtype='object')

In [9]:
#7
print(df.head(10))

       LoanID  Age  Income  LoanAmount  CreditScore  MonthsEmployed  \
0  I38PQUQS96   56   85994       50587          520              80
1  HPSK72WA7R   69   50432      124440          458              15
2  C1OZ6DPJ8Y   46   84208      129188          451              26
3  V2KKSFM3UN   32   31713       44799          743               0
4  EY08JDHTZP   60   20437        9139          633               8
5  A9S62RQ7US   25   90298       90448          720              18
6  H8GXPAOS71   38  111188      177025          429              80
7  0HGZQKJ36W   56  126802      155511          531              67
8  1R0N3LGNRJ   36   42053       92357          827              83
9  CM9L1GTT2P   40  132784      228510          480             114

   NumCreditLines  InterestRate  LoanTerm  DTIRatio    Education  \
0               4         15.23        36      0.44   Bachelor's
1               1          4.81        60      0.68     Master's
2               3         21.17        24      0.31     Master's
3               3          7.07        24      0.23  High School
4               4          6.51        48      0.73   Bachelor's
5               2         22.72        24      0.10  High School
6               1         19.11        12      0.16   Bachelor's
7               4          8.15        60      0.43          PhD
8               1         23.94        48      0.20   Bachelor's
9               4          9.09        48      0.33  High School

  EmploymentType MaritalStatus HasMortgage HasDependents LoanPurpose  \
0      Full-time      Divorced         Yes           Yes       Other
1      Full-time       Married          No            No       Other
2     Unemployed      Divorced         Yes           Yes        Auto
3      Full-time       Married          No            No    Business
4     Unemployed      Divorced          No           Yes        Auto
5     Unemployed        Single         Yes            No    Business
6     Unemployed        Single         Yes            No        Home
7      Full-time       Married          No            No        Home
8  Self-employed      Divorced         Yes            No   Education
9  Self-employed       Married         Yes            No       Other

  HasCoSigner  Default
0         Yes        0
1         Yes        0
2          No        1
3          No        0
4          No        0
5         Yes        1
6         Yes        0
7         Yes        0
8          No        1
9         Yes        0

In [10]:
#8
print(df.tail(10))

            LoanID  Age  Income  LoanAmount  CreditScore  MonthsEmployed  \
255337  DSL4O0KAWD   64   73743      140354          300               0
255338  6V8S5IUS63   68   21711      168231          352              78
255339  O6SWO6CBGB   51   69492      122962          348              66
255340  48LOOK4VR1   41   61809      119238          444              34
255341  AKXAXQN7PG   40  129890      116119          701              38
255342  8C6S86ESGC   19   37979      210682          541             109
255343  98R4KDHNND   32   51953      189899          511              14
255344  XQK1UUUNGP   56   84820      208294          597              70
255345  JAO28CPL4H   42   85109       60575          809              40
255346  ZTH91CGL0B   62   22418       18481          636             113

        NumCreditLines  InterestRate  LoanTerm  DTIRatio    Education  \
255337               2          4.12        12      0.24          PhD
255338               2          9.71        60      0.36          PhD
255339               2         10.83        48      0.27  High School
255340               2         19.99        36      0.31     Master's
255341               3          9.91        24      0.23  High School
255342               4         14.11        12      0.85   Bachelor's
255343               2         11.55        24      0.21  High School
255344               3          5.29        60      0.50  High School
255345               1         20.90        48      0.44  High School
255346               2          6.73        12      0.48   Bachelor's

       EmploymentType MaritalStatus HasMortgage HasDependents LoanPurpose  \
255337  Self-employed        Single         Yes            No   Education
255338      Full-time      Divorced         Yes           Yes        Home
255339      Part-time      Divorced          No            No        Home
255340      Part-time       Married         Yes           Yes        Auto
255341      Part-time      Divorced         Yes            No        Home
255342      Full-time       Married          No            No       Other
255343      Part-time      Divorced          No            No        Home
255344  Self-employed       Married         Yes           Yes        Auto
255345      Part-time        Single         Yes           Yes       Other
255346     Unemployed      Divorced         Yes            No   Education

       HasCoSigner  Default
255337         Yes        0
255338          No        0
255339          No        0
255340         Yes        0
255341         Yes        1
255342          No        0
255343          No        1
255344         Yes        0
255345          No        0
255346         Yes        0

In [5]:
#9
df['Default'].value_counts()

Default
0    225694
1     29653
Name: count, dtype: int64

In [16]:
#10
df['LoanAmount'].head(1)

0    50587
Name: LoanAmount, dtype: int64

In [21]:
#11
print(df["LoanAmount"].sum())

32576880572